[package]
name = "cargo-aoc"
version = "0.3.2"
authors = ["Grégory Obanos <gregory.obanos@gmail.com>", "Olivier Pinon <oliv.pinon@gmail.com>"]
description = "Cargo Advent of Code Helper"
license = "MIT/Apache-2.0"
repository = "https://github.com/gobanos/cargo-aoc"
readme = "../README.md"
edition = "2018"
include = ["Cargo.toml", "src/**/*", "template/**/*.tpl", "../README.md"]

[dependencies]
aoc-runner-internal = { path = "../aoc-runner-internal", version = "0.1.0" }
toml = "0.5.3"
clap = "2.33.0"
chrono = "0.4.9"
chrono-tz = "0.5.1"
reqwest = "0.9.21"
webbrowser = "0.5.2"
directories = "2.0.2"
camino = "1.0.5"
cargo_metadata = "0.14.1"
tera = "1.15.0"
